language: java
jdk:
  - openjdk11

branches:
  only:
    - development
env:
  - IMGNAME=java    

services:
  - docker
jobs:
 include:
   - stage: Build
     script:
      - mvn compile
   - stage: Test
     script:
      - mvn test
   - stage: Package
     script:
      - mvn package

after_success:
  - echo "successful"
  - docker build -t ${IMGNAME} .
  - docker login -u ${username} -p ${password}
  - docker images
  - docker tag  java:latest rishiray/my-java:1.0
  - docker push rishiray/my-java:1.0

notifications:
  email:
    recipients:
      - rishirai760@gmail.com
    on_success: always
    on_failure: always
