language: java
jdk:
  - openjdk11

branches:
  only:
    - development

services:
  - docker

script:
  - mvn compile
  - docker build -t my-image

after_success:
   - echo "successful"

notifications:
  email:
    recipients:
      - rishirai760@gmail.com
    on_success: always
    on_failure: always

   .
