language: java
jdk:
  - openjdk11

branches:
  only:
    - development
env:
  - IMGNAME=java    

services:
  - docker

script:
  - mvn compile
  - docker build -t ${IMGNAME} .

after_success:
  - echo "successful"
  - docker login -u ${username} -p ${password}
  - docker tag  ${IMGNAME}:latest my-java:1.0
  - docker push my-java:1.0

notifications:
  email:
    recipients:
      - rishirai760@gmail.com
    on_success: always
    on_failure: always
